# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  default:
    - step:
        name: Build
        image: gcc:6.1
        script:
          - cd phase0
          - make
    - step:
        name: Infer analysis
        image: tomasberanek/custom-infer:0.17.0
        size: 2x
        script:
          - cd phase0
          - make clean   #necessary
          - infer -- make
        after-script:
          - cd phase0 && make clean   #optional
